from __future__ import annotations

import inspect
import json
import math
import shutil
import time
import uuid
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal, Protocol, cast

import numpy as np
from PIL import Image

from r2v_data_v2.reconciliation import write_json_atomic
from r2v_data_v2.v3.reference_completion_benchmark import (
    ALLOWED_INPUT_ROOT,
    CompletionBenchmarkStats,
    CompletionCandidateSpec,
    CompletionManifestRecord,
    CompletionRunPolicy,
    HardCheckReport,
    QwenReferenceCompletionJudge,
    ReferenceCompletionJudge,
    ReferenceCompletionReview,
    ReferenceType,
    _load_source_rgba,
    _resolve_benchmark_root,
    _resolve_input_path,
    _save_png,
    _sha256_path,
    _synthetic_reject_review,
    _white_source,
    load_completion_manifest,
    run_completion_benchmark,
)

QWEN_COMPLETION_BACKEND = "qwen_image_edit_2511"
DEFAULT_QWEN_MODEL_PATH = Path(
    "/mnt/workspace/public/pretrained/Qwen/Qwen-Image-Edit-2511"
)
ALLOWED_QWEN_BENCHMARK_ROOT = (
    ALLOWED_INPUT_ROOT / "reference_completion_qwen_benchmarks"
).resolve()
DEFAULT_QWEN_SEEDS = (0,)
LEGACY_QWEN_SEEDS = (0, 17)
QwenCompletionCompositingMode = Literal["whole_canvas", "explicit_mask"]
DEFAULT_QWEN_COMPOSITING_MODE: QwenCompletionCompositingMode = "whole_canvas"
QwenCompletionMode = Literal["localized_raw", "whole_canvas", "explicit_mask"]
DEFAULT_QWEN_COMPLETION_MODE: QwenCompletionMode = "localized_raw"

DEFAULT_QWEN_LOCALIZED_SUBJECT_PROMPT = (
    "Complete only the missing local part of the same existing subject. "
    "Preserve its identity, appearance, pose, proportions, clothing, texture, "
    "and all visible characteristics. Do not generate a new instance, do not "
    "redraw the entire subject, and do not expand the composition. Only repair "
    "the locally incomplete region so the existing subject looks naturally "
    "continuous. Keep the background plain and unchanged."
)
DEFAULT_QWEN_LOCALIZED_OBJECT_PROMPT = (
    "Complete only the missing local part of the same existing object. Preserve "
    "its geometry, material, texture, color, scale, viewpoint, and all visible "
    "characteristics. Do not generate a second object, do not redesign the "
    "entire object, and do not expand the composition. Only repair the locally "
    "incomplete region so the existing object looks naturally continuous. Keep "
    "the background plain and unchanged."
)
DEFAULT_QWEN_LOCALIZED_GROUP_PROMPT = (
    "Complete only the missing local part of the same existing group. Preserve "
    "the visible members, arrangement, relationships, appearance, scale, "
    "viewpoint, and all visible characteristics. Do not add unrelated members, "
    "do not create a new group, and do not expand the composition. Only repair "
    "the locally incomplete region so the existing group looks naturally "
    "continuous. Keep the background plain and unchanged."
)
QWEN_LOCALIZED_PROMPT_EN_SHORT = (
    "Complete the missing parts in this image. "
    "Do not generate a new instance."
)
QWEN_LOCALIZED_PROMPT_ZH_SHORT = (
    "\u628a\u8fd9\u5f20\u56fe\u4e2d\u6b8b\u7f3a\u7684\u90e8\u5206\u8865\u5145\u5b8c\u6574\uff0c\u4e0d\u8981\u751f\u6210\u65b0\u7684\u5b9e\u4f8b"
)
DEFAULT_QWEN_LOCALIZED_NEGATIVE_PROMPT = " "

DEFAULT_QWEN_SUBJECT_COMPLETION_PROMPT = (
    "Complete the missing parts of the same single person shown in this image. "
    "Preserve the person's identity, face, hairstyle, clothing, accessories, "
    "pose, body proportions, lighting, perspective, and all visible appearance "
    "details. Extend only the incomplete body and clothing naturally into the "
    "empty region. Do not create another person, another face, duplicate body "
    "parts, new clothing, or new foreground objects. Do not alter the already "
    "visible person. Keep the background plain white."
)
DEFAULT_QWEN_SUBJECT_COMPLETION_NEGATIVE_PROMPT = (
    "second person, extra person, different person, different face, duplicate "
    "face, duplicate body, extra arms, extra hands, extra legs, disconnected "
    "limbs, deformed anatomy, identity change, different clothing, new "
    "foreground object, text, watermark, logo"
)

QWEN_WHOLE_CANVAS_JUDGE_ADDENDUM = """This candidate was generated by a
whole-image editor that may edit the entire expanded canvas. The original
visible person pixels were restored exactly by code after generation. Judge
whether the newly generated area naturally completes that same person. A white
or near-white background and a slight natural shadow are allowed. Reject a
second person, a different identity, a new face, new clothing, a new scene, a
new salient object, text, a logo, or a watermark. Reject obvious vertical or
diagonal cut boundaries. Newly generated anatomy, pose, and clothing must
continue naturally from the restored person. Reject isolated clothing
fragments or an incomplete body."""

QWEN_LOCALIZED_JUDGE_SYSTEM_PROMPT = """You judge a localized entity-reference
completion benchmark. This task repairs only a genuinely missing local part of
the same existing entity; it is not full-instance reconstruction. Do not reject
a candidate merely because it does not produce a complete body, complete object,
or expanded group. A small completion is sufficient when the missing local part
is repaired naturally.

Require the same entity instance, a plain unchanged background, stable overall
composition, and no major redraw of already visible content. Reject an extra
instance, composition expansion, a complex background or new scene, an obvious
seam, ghosting, repeated structure, or unrelated new content. Return one strict
JSON object containing only verdict, visible_source_preserved,
same_entity_continued, identity_preserved, exactly_one_entity,
completion_plausible, completion_useful, no_occluder_reconstructed,
no_new_salient_entity, boundary_clean, reference_usable, and reason. verdict is
accept if and only if every boolean is true. Return JSON only."""

_LOCALIZED_JUDGE_TYPE_GUIDANCE: dict[ReferenceType, str] = {
    "subject": (
        "For a subject, preserve the same identity and appearance. Reject a "
        "second subject, extra body, face, or limb, or inconsistent clothing, "
        "pose, or silhouette."
    ),
    "object": (
        "For an object, preserve the same instance, geometry, material, texture, "
        "and color. Reject a second object or a redesigned object."
    ),
    "group": (
        "For a group, preserve the existing members, arrangement, and "
        "relationships. Reject unrelated new members or a replacement group or "
        "scene."
    ),
}

_DEFAULT_LOCALIZED_PROMPTS: dict[ReferenceType, str] = {
    "subject": DEFAULT_QWEN_LOCALIZED_SUBJECT_PROMPT,
    "object": DEFAULT_QWEN_LOCALIZED_OBJECT_PROMPT,
    "group": DEFAULT_QWEN_LOCALIZED_GROUP_PROMPT,
}

_REVIEW_BOOLEAN_FIELDS = (
    "visible_source_preserved",
    "same_entity_continued",
    "identity_preserved",
    "exactly_one_entity",
    "completion_plausible",
    "completion_useful",
    "no_occluder_reconstructed",
    "no_new_salient_entity",
    "boundary_clean",
    "reference_usable",
)


class QwenReferenceCompletionBackend(Protocol):
    def complete(
        self,
        *,
        input_rgb: Image.Image,
        entity_phrase: str,
        seed: int,
        prompt: str,
        negative_prompt: str,
    ) -> Image.Image: ...


class QwenLocalizedCompletionJudge(Protocol):
    def review(
        self,
        *,
        source_rgba: Image.Image,
        candidate_rgb: Image.Image,
        entity_phrase: str,
        reference_type: ReferenceType,
    ) -> ReferenceCompletionReview: ...


@dataclass(frozen=True)
class QwenImageEdit2511CompletionConfig:
    model_path: Path = DEFAULT_QWEN_MODEL_PATH
    device: str = "cuda"
    dtype: str = "bfloat16"
    num_inference_steps: int = 40
    true_cfg_scale: float = 4.0
    guidance_scale: float = 1.0
    local_files_only: bool = True
    canvas_expand_ratio: float = 0.75
    lateral_padding_ratio: float = 0.20
    mask_overlap_pixels: int = 0
    model_min_side: int = 1024
    model_multiple: int = 16
    mode: QwenCompletionMode = DEFAULT_QWEN_COMPLETION_MODE

    @property
    def compositing_mode(self) -> QwenCompletionCompositingMode | None:
        if self.mode == "localized_raw":
            return None
        return self.mode

    def validate(self) -> None:
        if not isinstance(self.model_path, Path):
            raise TypeError("model_path must be a pathlib.Path")
        if not self.model_path.expanduser().resolve(strict=False).is_dir():
            raise FileNotFoundError(
                f"Qwen Image Edit model path does not exist: {self.model_path}"
            )
        if not isinstance(self.device, str) or not self.device.strip():
            raise ValueError("device must be non-empty")
        if self.dtype not in {"float16", "bfloat16", "float32"}:
            raise ValueError("dtype must be float16, bfloat16, or float32")
        if self.local_files_only is not True:
            raise ValueError("Qwen completion requires local_files_only=true")
        if self.mode not in {"localized_raw", "whole_canvas", "explicit_mask"}:
            raise ValueError("unsupported Qwen completion mode")
        if (
            not isinstance(self.num_inference_steps, int)
            or isinstance(self.num_inference_steps, bool)
            or self.num_inference_steps <= 0
        ):
            raise ValueError("num_inference_steps must be a positive integer")
        for name, value in (
            ("true_cfg_scale", self.true_cfg_scale),
            ("guidance_scale", self.guidance_scale),
        ):
            if not isinstance(value, (int, float)) or isinstance(value, bool):
                raise TypeError(f"{name} must be numeric")
            if not math.isfinite(value) or value < 0:
                raise ValueError(f"{name} must be finite and non-negative")
        if self.mode != "localized_raw":
            for name, value in (
                ("canvas_expand_ratio", self.canvas_expand_ratio),
                ("lateral_padding_ratio", self.lateral_padding_ratio),
            ):
                if not isinstance(value, (int, float)) or isinstance(value, bool):
                    raise TypeError(f"{name} must be numeric")
                if not math.isfinite(value) or value < 0:
                    raise ValueError(f"{name} must be finite and non-negative")
            if self.canvas_expand_ratio <= 0:
                raise ValueError("canvas_expand_ratio must be positive")
            if (
                not isinstance(self.mask_overlap_pixels, int)
                or isinstance(self.mask_overlap_pixels, bool)
                or self.mask_overlap_pixels < 0
            ):
                raise ValueError(
                    "mask_overlap_pixels must be a non-negative integer"
                )
            for name, value in (
                ("model_min_side", self.model_min_side),
                ("model_multiple", self.model_multiple),
            ):
                if (
                    not isinstance(value, int)
                    or isinstance(value, bool)
                    or value <= 0
                ):
                    raise ValueError(f"{name} must be a positive integer")


def _supports_explicit_parameter(callable_object: Any, name: str) -> bool:
    return name in inspect.signature(callable_object).parameters


def _supports_parameter(callable_object: Any, name: str) -> bool:
    parameters = inspect.signature(callable_object).parameters
    return name in parameters or any(
        parameter.kind is inspect.Parameter.VAR_KEYWORD
        for parameter in parameters.values()
    )


def _require_parameters(
    callable_object: Any,
    names: tuple[str, ...],
    *,
    operation: str,
) -> None:
    missing = [name for name in names if not _supports_parameter(callable_object, name)]
    if missing:
        raise RuntimeError(f"installed API lacks {operation} parameters {missing}")


class QwenImageEdit2511ReferenceCompletionBackend:
    """Local Qwen image-edit backend for raw and historical completion modes."""

    def __init__(
        self,
        config: QwenImageEdit2511CompletionConfig,
        *,
        pipeline: Any | None = None,
        torch_module: Any | None = None,
    ) -> None:
        config.validate()
        if (pipeline is None) != (torch_module is None):
            raise ValueError("pipeline and torch_module must be injected together")
        self.config = config
        self._pipeline = pipeline
        self._torch = torch_module
        self._load_error: BaseException | None = None

    def _load(self) -> None:
        import torch
        from diffusers import QwenImageEditPlusPipeline

        model_path = self.config.model_path.expanduser().resolve()
        dtype = getattr(torch, self.config.dtype, None)
        if dtype is None:
            raise RuntimeError(
                f"installed torch does not provide dtype {self.config.dtype}"
            )
        dtype_parameter = (
            "dtype"
            if _supports_explicit_parameter(
                QwenImageEditPlusPipeline.from_pretrained,
                "dtype",
            )
            else "torch_dtype"
        )
        _require_parameters(
            QwenImageEditPlusPipeline.from_pretrained,
            (dtype_parameter, "local_files_only"),
            operation="QwenImageEditPlusPipeline.from_pretrained",
        )
        pipeline = QwenImageEditPlusPipeline.from_pretrained(
            str(model_path),
            **{
                dtype_parameter: dtype,
                "local_files_only": True,
            },
        )
        progress = getattr(pipeline, "set_progress_bar_config", None)
        if callable(progress):
            progress(disable=True)
        to_method = getattr(pipeline, "to", None)
        if not callable(to_method):
            raise TypeError("Qwen Image Edit pipeline has no device transfer API")
        self._pipeline = to_method(self.config.device)
        self._torch = torch

    def _ensure_loaded(self) -> None:
        if self._pipeline is not None:
            return
        if self._load_error is not None:
            raise RuntimeError(
                "Qwen completion backend previously failed to load"
            ) from self._load_error
        try:
            self._load()
        except Exception as exc:
            self._load_error = exc
            raise

    def complete(
        self,
        *,
        input_rgb: Image.Image,
        entity_phrase: str,
        seed: int,
        prompt: str,
        negative_prompt: str,
    ) -> Image.Image:
        if not isinstance(input_rgb, Image.Image) or input_rgb.mode != "RGB":
            raise ValueError("Qwen completion input must be an RGB image")
        if not entity_phrase.strip():
            raise ValueError("entity_phrase must be non-empty")
        if not isinstance(seed, int) or isinstance(seed, bool) or seed < 0:
            raise ValueError("seed must be a non-negative integer")
        if not isinstance(prompt, str) or not prompt.strip():
            raise ValueError("Qwen completion prompt must be non-empty")
        if not isinstance(negative_prompt, str) or not negative_prompt:
            raise ValueError("Qwen completion negative prompt must be non-empty")
        self._ensure_loaded()
        if self._pipeline is None or self._torch is None:
            raise RuntimeError("Qwen completion backend is unavailable")

        generator = self._torch.Generator(device=self.config.device).manual_seed(seed)
        parameters = {
            "image": [input_rgb],
            "prompt": prompt,
            "negative_prompt": negative_prompt,
            "generator": generator,
            "true_cfg_scale": self.config.true_cfg_scale,
            "guidance_scale": self.config.guidance_scale,
            "num_inference_steps": self.config.num_inference_steps,
            "num_images_per_prompt": 1,
        }
        if self.config.mode != "localized_raw":
            parameters["height"] = input_rgb.height
            parameters["width"] = input_rgb.width
        _require_parameters(
            self._pipeline.__call__,
            tuple(parameters),
            operation="QwenImageEditPlusPipeline.__call__",
        )
        result = self._pipeline(**parameters)
        images = getattr(result, "images", None)
        if (
            not isinstance(images, (list, tuple))
            or not images
            or not isinstance(images[0], Image.Image)
        ):
            raise TypeError("Qwen completion backend did not return a PIL image")
        output = images[0]
        if self.config.mode != "localized_raw" and output.mode != "RGB":
            raise TypeError("Qwen completion output must use RGB mode")
        if self.config.mode != "localized_raw" and output.size != input_rgb.size:
            raise RuntimeError(
                "Qwen completion output dimensions do not match model input"
            )
        return output.convert("RGB").copy()

    def close(self) -> None:
        pipeline = self._pipeline
        self._pipeline = None
        if pipeline is not None:
            del pipeline
        torch = self._torch
        self._torch = None
        if (
            torch is not None
            and hasattr(torch, "cuda")
            and torch.cuda.is_available()
        ):
            torch.cuda.empty_cache()


class QwenLocalizedReferenceCompletionJudge(QwenReferenceCompletionJudge):
    """Two-image structured judge for mode-agnostic localized completion."""

    def _messages(
        self,
        *,
        source_rgba: Image.Image,
        completion_canvas: Image.Image,
        completion_mask: Image.Image,
        candidate_rgb: Image.Image,
        request_text: str,
        completion_region_label: str,
        system_prompt_addendum: str,
    ) -> list[dict[str, object]]:
        del completion_canvas, completion_mask, completion_region_label
        content: list[dict[str, object]] = [{"type": "text", "text": request_text}]
        for label, image in (
            ("Image 1: source entity on white", _white_source(source_rgba)),
            ("Image 2: localized raw candidate", candidate_rgb),
        ):
            content.append({"type": "text", "text": label})
            content.append(
                {
                    "type": "image_url",
                    "image_url": {"url": _png_data_url_local(image)},
                }
            )
        system_prompt = QWEN_LOCALIZED_JUDGE_SYSTEM_PROMPT
        if system_prompt_addendum.strip():
            system_prompt += "\n\n" + system_prompt_addendum.strip()
        return [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": content},
        ]

    def review(
        self,
        *,
        source_rgba: Image.Image,
        candidate_rgb: Image.Image,
        entity_phrase: str,
        reference_type: ReferenceType,
    ) -> ReferenceCompletionReview:
        if reference_type not in _LOCALIZED_JUDGE_TYPE_GUIDANCE:
            raise ValueError("unsupported localized completion reference_type")
        if candidate_rgb.mode != "RGB":
            raise ValueError("localized completion judge candidate must be RGB")
        return super().review(
            source_rgba=source_rgba,
            completion_canvas=candidate_rgb.copy(),
            completion_mask=Image.new("L", candidate_rgb.size, 255),
            candidate_rgb=candidate_rgb,
            entity_phrase=entity_phrase,
            reference_type=reference_type,
            completion_region_label="localized raw candidate",
            system_prompt_addendum=_LOCALIZED_JUDGE_TYPE_GUIDANCE[reference_type],
        )


def _png_data_url_local(image: Image.Image) -> str:
    import base64
    import io

    buffer = io.BytesIO()
    image.save(buffer, format="PNG")
    encoded = base64.b64encode(buffer.getvalue()).decode("ascii")
    return f"data:image/png;base64,{encoded}"


def _localized_prompt(
    reference_type: ReferenceType,
    override: str | None,
) -> tuple[str, Literal["en", "zh", "custom"]]:
    if override is None:
        return _DEFAULT_LOCALIZED_PROMPTS[reference_type], "en"
    prompt = override.strip()
    if not prompt:
        raise ValueError("Qwen completion prompt must be non-empty")
    language: Literal["en", "zh", "custom"]
    if prompt == QWEN_LOCALIZED_PROMPT_EN_SHORT:
        language = "en"
    elif prompt == QWEN_LOCALIZED_PROMPT_ZH_SHORT:
        language = "zh"
    else:
        language = "custom"
    return prompt, language


def _localized_hard_check(
    *,
    generated: object,
    input_rgb: Image.Image,
    input_path: Path,
    candidate_path: Path,
    source_path: Path,
    source_sha256: str,
) -> tuple[Image.Image | None, str | None, HardCheckReport]:
    checks = {
        "pipeline_returned_pil_image": isinstance(generated, Image.Image),
        "output_convertible_to_rgb": False,
        "output_dimensions_positive": False,
        "output_pixels_uint8": False,
        "output_has_no_invalid_values": False,
        "output_not_constant": False,
        "output_differs_from_input": False,
        "source_file_unchanged": _sha256_path(source_path) == source_sha256,
        "published_input_reopenable": False,
        "published_candidate_reopenable": False,
        "candidate_sha256_recorded": False,
    }
    candidate: Image.Image | None = None
    converted_candidate: Image.Image | None = None
    candidate_sha256: str | None = None
    try:
        with Image.open(input_path) as opened_input:
            opened_input.load()
            checks["published_input_reopenable"] = (
                opened_input.format == "PNG"
                and opened_input.mode == "RGB"
                and opened_input.size == input_rgb.size
            )
    except (OSError, ValueError):
        pass

    if isinstance(generated, Image.Image):
        try:
            converted_candidate = generated.convert("RGB")
            checks["output_convertible_to_rgb"] = True
        except (OSError, ValueError):
            converted_candidate = None
    if converted_candidate is not None:
        checks["output_dimensions_positive"] = (
            converted_candidate.width > 0 and converted_candidate.height > 0
        )
        pixels = np.asarray(converted_candidate)
        checks["output_pixels_uint8"] = pixels.dtype == np.uint8
        checks["output_has_no_invalid_values"] = bool(np.isfinite(pixels).all())
        checks["output_not_constant"] = bool(
            pixels.size
            and np.unique(pixels.reshape(-1, 3), axis=0).shape[0] > 1
        )
        checks["output_differs_from_input"] = (
            converted_candidate.size != input_rgb.size
            or not np.array_equal(pixels, np.asarray(input_rgb, dtype=np.uint8))
        )
        if checks["output_dimensions_positive"]:
            _save_png(candidate_path, converted_candidate)
            with Image.open(candidate_path) as opened_candidate:
                opened_candidate.load()
                checks["published_candidate_reopenable"] = (
                    opened_candidate.format == "PNG"
                    and opened_candidate.mode == "RGB"
                    and opened_candidate.size == converted_candidate.size
                )
            candidate_sha256 = _sha256_path(candidate_path)
            checks["candidate_sha256_recorded"] = (
                len(candidate_sha256) == 64
                and candidate_sha256 == _sha256_path(candidate_path)
            )
            candidate = converted_candidate

    reason_codes = {
        "pipeline_returned_pil_image": "pipeline_did_not_return_pil_image",
        "output_convertible_to_rgb": "candidate_not_convertible_to_rgb",
        "output_dimensions_positive": "candidate_dimensions_not_positive",
        "output_pixels_uint8": "candidate_pixels_not_uint8",
        "output_has_no_invalid_values": "candidate_has_invalid_pixels",
        "output_not_constant": "candidate_is_constant",
        "output_differs_from_input": "candidate_unchanged_from_input",
        "source_file_unchanged": "source_file_changed",
        "published_input_reopenable": "published_input_not_reopenable",
        "published_candidate_reopenable": "published_candidate_not_reopenable",
        "candidate_sha256_recorded": "candidate_sha256_not_recorded",
    }
    reasons = tuple(
        reason_codes[name] for name, passed in checks.items() if not passed
    )
    return candidate, candidate_sha256, HardCheckReport(not reasons, checks, reasons)


def _validate_seeds(seeds: tuple[int, ...]) -> tuple[int, ...]:
    if not seeds or len(set(seeds)) != len(seeds):
        raise ValueError("Qwen completion seeds must be non-empty and unique")
    if any(
        not isinstance(seed, int) or isinstance(seed, bool) or seed < 0
        for seed in seeds
    ):
        raise ValueError("Qwen completion seeds must be non-negative integers")
    return seeds


def _validate_qwen_record(
    record: CompletionManifestRecord,
    *,
    mode: QwenCompletionMode,
) -> None:
    if mode != "localized_raw" and record.reference_type != "subject":
        raise ValueError("Qwen completion supports only reference_type=subject")
    if mode == "explicit_mask" and record.completion_mask_path is None:
        raise ValueError("Qwen completion requires completion_mask_path")


def _full_prompt(prompt: str, entity_phrase: str) -> str:
    return f"{prompt.strip()} Entity description: {entity_phrase.strip()}."


def _localized_summary(
    benchmark_root: Path,
    results: tuple[dict[str, object], ...],
    stats: CompletionBenchmarkStats,
) -> dict[str, object]:
    reference_types: Counter[str] = Counter()
    hard_rejections: Counter[str] = Counter()
    judge_rejections: Counter[str] = Counter()
    manual_review_pending = 0
    for result in results:
        reference_types[str(result["reference_type"])] += 1
        manual_review_pending += int(result["status"] == "manual_review_pending")
        hard_check = result.get("hard_check")
        if not isinstance(hard_check, dict):
            raise TypeError("localized completion hard_check must be an object")
        if hard_check.get("status") == "failed":
            reasons = hard_check.get("reasons")
            if not isinstance(reasons, list):
                raise TypeError("localized hard-check reasons must be a list")
            hard_rejections.update(str(reason) for reason in reasons)
            continue
        if result.get("judge_status") != "reviewed" or (
            result.get("judge_verdict") != "reject"
        ):
            continue
        review_path = result.get("review_path")
        if not isinstance(review_path, str):
            raise TypeError("localized completion review_path must be a string")
        review = json.loads(
            (benchmark_root / str(result["sample_id"]) / review_path).read_text(
                encoding="utf-8"
            )
        )
        for field_name in _REVIEW_BOOLEAN_FIELDS:
            if review.get(field_name) is False:
                judge_rejections[field_name] += 1
    return {
        "backend": QWEN_COMPLETION_BACKEND,
        "mode": "localized_raw",
        "processed": stats.processed,
        "reference_type_counts": dict(sorted(reference_types.items())),
        "manual_review_pending": manual_review_pending,
        "rejected": stats.rejected,
        "accepted": 0,
        "hard_check_rejection_counts": dict(sorted(hard_rejections.items())),
        "judge_rejection_flag_counts": dict(sorted(judge_rejections.items())),
    }


def _process_localized_record(
    record: CompletionManifestRecord,
    *,
    source_path: Path,
    benchmark_root: Path,
    config: QwenImageEdit2511CompletionConfig,
    backend: QwenReferenceCompletionBackend,
    judge: QwenLocalizedCompletionJudge,
    prompt_override: str | None,
    negative_prompt: str,
    seed: int,
) -> dict[str, object]:
    source_rgba, source_bytes, source_sha256 = _load_source_rgba(source_path)
    input_rgb = _white_source(source_rgba)
    prompt, prompt_language = _localized_prompt(
        record.reference_type,
        prompt_override,
    )
    final_directory = benchmark_root / record.sample_id
    temporary = benchmark_root / f".{record.sample_id}.tmp-{uuid.uuid4().hex}"
    temporary.mkdir(parents=False, exist_ok=False)
    started = time.perf_counter()
    candidate_name = f"candidate_qwen_localized_seed_{seed}.png"
    review_name = f"review_qwen_localized_seed_{seed}.json"
    try:
        (temporary / "source_rgba.png").write_bytes(source_bytes)
        input_path = temporary / "input_source_white.png"
        _save_png(input_path, input_rgb)
        generation_error: str | None = None
        try:
            generated: object = backend.complete(
                input_rgb=input_rgb.copy(),
                entity_phrase=record.entity_phrase,
                seed=seed,
                prompt=prompt,
                negative_prompt=negative_prompt,
            )
        except (OSError, RuntimeError, TypeError, ValueError) as exc:
            generated = None
            generation_error = f"backend_failed: {exc}"
        candidate, candidate_sha256, hard_check = _localized_hard_check(
            generated=generated,
            input_rgb=input_rgb,
            input_path=input_path,
            candidate_path=temporary / candidate_name,
            source_path=source_path,
            source_sha256=source_sha256,
        )
        if generation_error is not None:
            hard_check = HardCheckReport(
                passed=False,
                checks=hard_check.checks,
                reasons=(generation_error, *hard_check.reasons),
            )

        judge_status = "not_run"
        if not hard_check.passed or candidate is None:
            reason = "hard_check_failed: " + "; ".join(hard_check.reasons)
            review = _synthetic_reject_review(reason)
        else:
            try:
                review = judge.review(
                    source_rgba=source_rgba.copy(),
                    candidate_rgb=candidate.copy(),
                    entity_phrase=record.entity_phrase,
                    reference_type=record.reference_type,
                )
                if not isinstance(review, ReferenceCompletionReview):
                    raise TypeError("judge must return ReferenceCompletionReview")
                judge_status = "reviewed"
                reason = review.reason
            except (OSError, RuntimeError, TypeError, ValueError) as exc:
                judge_status = "failed_closed"
                reason = f"judge_failed: {exc}"
                review = _synthetic_reject_review(reason)
        write_json_atomic(temporary / review_name, review.model_dump(mode="json"))
        status = (
            "manual_review_pending"
            if hard_check.passed and review.verdict == "accept"
            else "rejected"
        )
        if _sha256_path(source_path) != source_sha256:
            raise RuntimeError(
                "source reference changed during localized completion benchmark"
            )
        result: dict[str, object] = {
            "backend": QWEN_COMPLETION_BACKEND,
            "mode": "localized_raw",
            "sample_id": record.sample_id,
            "clip_uid": record.clip_uid,
            "entity_id": record.entity_id,
            "reference_type": record.reference_type,
            "entity_phrase": record.entity_phrase,
            "source_path": str(source_path),
            "source_sha256": source_sha256,
            "input_path": "input_source_white.png",
            "input_size": list(input_rgb.size),
            "prompt": prompt,
            "prompt_language": prompt_language,
            "negative_prompt": negative_prompt,
            "seed": seed,
            "num_inference_steps": config.num_inference_steps,
            "true_cfg_scale": config.true_cfg_scale,
            "guidance_scale": config.guidance_scale,
            "candidate_path": candidate_name if candidate is not None else None,
            "candidate_sha256": candidate_sha256,
            "output_size": list(candidate.size) if candidate is not None else None,
            "hard_check": hard_check.to_dict(),
            "judge_status": judge_status,
            "judge_verdict": review.verdict,
            "review_path": review_name,
            "status": status,
            "manual_review_required": True,
            "accepted_candidate": None,
            "localized_completion": True,
            "full_instance_reconstruction_requested": False,
            "canvas_expansion_used": False,
            "completion_mask_used": False,
            "visible_pixel_restore_used": False,
            "height_width_forced": False,
            "entity_phrase_appended_to_prompt": False,
            "runtime_seconds": time.perf_counter() - started,
            "reason": reason,
        }
        write_json_atomic(temporary / "result.json", result)
        temporary.replace(final_directory)
        return result
    except Exception:
        shutil.rmtree(temporary, ignore_errors=True)
        raise


def _run_localized_completion_benchmark(
    *,
    manifest_path: Path,
    benchmark_root: Path,
    config: QwenImageEdit2511CompletionConfig,
    backend: QwenReferenceCompletionBackend,
    judge: QwenLocalizedCompletionJudge,
    prompt: str | None,
    negative_prompt: str,
    seeds: tuple[int, ...],
) -> CompletionBenchmarkStats:
    if len(seeds) != 1:
        raise ValueError("localized_raw requires exactly one seed")
    resolved_root = _resolve_benchmark_root(
        benchmark_root,
        allowed_benchmark_root=ALLOWED_QWEN_BENCHMARK_ROOT,
    )
    records = load_completion_manifest(manifest_path)
    preflights: list[Path] = []
    for record in records:
        _validate_qwen_record(record, mode="localized_raw")
        source_path = _resolve_input_path(
            record.source_rgba_path,
            field_name="source_rgba_path",
        )
        _load_source_rgba(source_path)
        preflights.append(source_path)
    resolved_root.mkdir(parents=True, exist_ok=False)
    results = tuple(
        _process_localized_record(
            record,
            source_path=source_path,
            benchmark_root=resolved_root,
            config=config,
            backend=backend,
            judge=judge,
            prompt_override=prompt,
            negative_prompt=negative_prompt,
            seed=seeds[0],
        )
        for record, source_path in zip(records, preflights)
    )
    stats = CompletionBenchmarkStats(
        processed=len(results),
        accepted=0,
        rejected=sum(result["status"] == "rejected" for result in results),
    )
    write_json_atomic(
        resolved_root / "benchmark_summary.json",
        _localized_summary(resolved_root, results, stats),
    )
    return stats


def _summary_from_results(
    benchmark_root: Path,
    results: tuple[dict[str, object], ...],
    stats: CompletionBenchmarkStats,
) -> dict[str, object]:
    hard_rejections: Counter[str] = Counter()
    judge_rejections: Counter[str] = Counter()
    compositing_modes: Counter[str] = Counter()
    for result in results:
        sample_id = str(result["sample_id"])
        compositing_modes[str(result["compositing_mode"])] += 1
        attempts = result.get("attempts")
        if not isinstance(attempts, list):
            raise TypeError("completion result attempts must be a list")
        for attempt in attempts:
            if not isinstance(attempt, dict):
                raise TypeError("completion result attempt must be an object")
            hard_check = attempt.get("hard_check")
            if not isinstance(hard_check, dict):
                raise TypeError("completion hard_check must be an object")
            if hard_check.get("status") == "failed":
                reasons = hard_check.get("reasons")
                if not isinstance(reasons, list):
                    raise TypeError("completion hard-check reasons must be a list")
                hard_rejections.update(str(reason) for reason in reasons)
                continue
            if attempt.get("judge_status") != "reviewed" or (
                attempt.get("judge_verdict") != "reject"
            ):
                continue
            review_path = attempt.get("review_path")
            if not isinstance(review_path, str):
                raise TypeError("completion review_path must be a string")
            review = json.loads(
                (benchmark_root / sample_id / review_path).read_text(
                    encoding="utf-8"
                )
            )
            for field_name in _REVIEW_BOOLEAN_FIELDS:
                if review.get(field_name) is False:
                    judge_rejections[field_name] += 1
    return {
        "backend": QWEN_COMPLETION_BACKEND,
        "processed": stats.processed,
        "accepted": stats.accepted,
        "rejected": stats.rejected,
        "hard_check_rejection_counts": dict(sorted(hard_rejections.items())),
        "judge_rejection_flag_counts": dict(sorted(judge_rejections.items())),
        "compositing_mode_counts": dict(sorted(compositing_modes.items())),
    }


def run_qwen_reference_completion_benchmark(
    *,
    manifest_path: Path,
    benchmark_root: Path,
    config: QwenImageEdit2511CompletionConfig,
    backend: QwenReferenceCompletionBackend,
    judge: ReferenceCompletionJudge | QwenLocalizedCompletionJudge,
    prompt: str | None = None,
    negative_prompt: str | None = None,
    seeds: tuple[int, ...] | None = None,
) -> CompletionBenchmarkStats:
    config.validate()
    selected_seeds = _validate_seeds(
        seeds
        if seeds is not None
        else (DEFAULT_QWEN_SEEDS if config.mode == "localized_raw" else LEGACY_QWEN_SEEDS)
    )
    if config.mode == "localized_raw":
        if prompt is not None and not prompt.strip():
            raise ValueError("Qwen completion prompt must be non-empty")
        selected_negative_prompt = (
            DEFAULT_QWEN_LOCALIZED_NEGATIVE_PROMPT
            if negative_prompt is None
            else negative_prompt
        )
        if not isinstance(selected_negative_prompt, str) or not selected_negative_prompt:
            raise ValueError("Qwen completion negative prompt must be non-empty")
        return _run_localized_completion_benchmark(
            manifest_path=manifest_path,
            benchmark_root=benchmark_root,
            config=config,
            backend=backend,
            judge=cast(QwenLocalizedCompletionJudge, judge),
            prompt=prompt,
            negative_prompt=selected_negative_prompt,
            seeds=selected_seeds,
        )

    selected_prompt = (
        DEFAULT_QWEN_SUBJECT_COMPLETION_PROMPT if prompt is None else prompt.strip()
    )
    selected_negative_prompt = (
        DEFAULT_QWEN_SUBJECT_COMPLETION_NEGATIVE_PROMPT
        if negative_prompt is None
        else negative_prompt.strip()
    )
    if not selected_prompt:
        raise ValueError("Qwen completion prompt must be non-empty")
    if not selected_negative_prompt:
        raise ValueError("Qwen completion negative prompt must be non-empty")
    compositing_mode = cast(QwenCompletionCompositingMode, config.mode)
    if compositing_mode == "whole_canvas":
        policy = CompletionRunPolicy(
            candidate_region_kind="editable_region",
            preserve_outside_candidate_region=False,
            region_artifact_name="editable_region.png",
            judge_region_label=(
                "editable region; this is not a model input mask"
            ),
            judge_system_prompt_addendum=QWEN_WHOLE_CANVAS_JUDGE_ADDENDUM,
        )
        result_metadata: dict[str, object] = {
            "backend": QWEN_COMPLETION_BACKEND,
            "mode": compositing_mode,
            "compositing_mode": compositing_mode,
            "completion_mask_mode": None,
            "completion_mask_source_path": None,
            "completion_mask_source_sha256": None,
            "completion_mask_area_ratio": None,
            "editable_region_path": "editable_region.png",
        }
    else:
        policy = CompletionRunPolicy()
        result_metadata = {
            "backend": QWEN_COMPLETION_BACKEND,
            "mode": compositing_mode,
            "compositing_mode": compositing_mode,
            "editable_region_path": None,
        }

    def candidate_factory(
        record: CompletionManifestRecord,
    ) -> tuple[CompletionCandidateSpec, ...]:
        final_prompt = _full_prompt(selected_prompt, record.entity_phrase)
        return tuple(
            CompletionCandidateSpec(
                file_stem=f"qwen_seed_{seed}",
                seed=seed,
                prompt=final_prompt,
                negative_prompt=selected_negative_prompt,
                attempt_metadata={
                    "backend": QWEN_COMPLETION_BACKEND,
                    "candidate_id": f"qwen_seed_{seed}",
                    "seed": seed,
                    "prompt": final_prompt,
                    "negative_prompt": selected_negative_prompt,
                    "compositing_mode": compositing_mode,
                },
                selection_metadata={
                    "backend": QWEN_COMPLETION_BACKEND,
                    "candidate_id": f"qwen_seed_{seed}",
                    "seed": seed,
                },
            )
            for seed in selected_seeds
        )

    def generate_candidate(
        *,
        record: CompletionManifestRecord,
        candidate: CompletionCandidateSpec,
        input_rgb: Image.Image,
        candidate_region: Image.Image,
    ) -> Image.Image:
        # Qwen edits one whole RGB image. The region is never sent to the model.
        del candidate_region
        return backend.complete(
            input_rgb=input_rgb,
            entity_phrase=record.entity_phrase,
            seed=candidate.seed,
            prompt=candidate.prompt,
            negative_prompt=candidate.negative_prompt,
        )

    run = run_completion_benchmark(
        manifest_path=manifest_path,
        benchmark_root=benchmark_root,
        allowed_benchmark_root=ALLOWED_QWEN_BENCHMARK_ROOT,
        config=config,
        judge=judge,
        candidate_factory=candidate_factory,
        generate_candidate=generate_candidate,
        record_validator=lambda record: _validate_qwen_record(
            record,
            mode=compositing_mode,
        ),
        result_metadata=result_metadata,
        policy=policy,
    )
    resolved_root = benchmark_root.expanduser().resolve()
    write_json_atomic(
        resolved_root / "benchmark_summary.json",
        _summary_from_results(resolved_root, run.results, run.stats),
    )
    return run.stats
